name       : foma
version    : 0.9.18
release    : 2
source     :
    - https://bitbucket.org/mhulden/foma/downloads/foma-0.9.18.tar.gz : cb380f43e86fc7b3d4e43186db3e7cff8f2417e18ea69cc991e466a3907d8cbd
license    : GPL-2.0
component  : programming
summary    : Foma is a multi-purpose finite-state toolkit designed for applications ranging from natural language processing and research in automata theory.
description: |
    Foma is a multi-purpose finite-state toolkit designed for applications ranging from natural language processing and research in automata theory.
builddeps  :
    - pkgconfig(vte-2.91)
setup      : |
    sed -i 's:-ltermcap::g' Makefile
build      : |
    %make prefix=${installdir}/usr CFLAGS="$CFLAGS -fcommon"
install    : |-
    %make_install prefix=${installdir}/usr
    rm $installdir/usr/lib/*.a
